### ISSUE TITLE
[test-infra] Wire native tests into build + add CI (unblocks TDD)

### ISSUE THREAD

**Issue by kihyun1998** [kihyun1998/x509_cert_store#12]
## Summary

Native tests currently cannot run at all: they are not wired into any build target, there is no CI, and one existing test is stale. This blocks any real TDD/red-green workflow on the native layers.

## Findings

1. **Windows tests are never compiled.** `windows/CMakeLists.txt` only defines the plugin SHARED library — there is no test target referencing `windows/test/x509_cert_store_plugin_test.cpp`. Any gtest in that file is orphaned and cannot run (e.g. the `AddCertificateRejectsEmptyData` regression test added for #7).
2. **Stale test.** `windows/test/x509_cert_store_plugin_test.cpp` still tests `GetPlatformVersion`, but the plugin returns `NotImplemented` for every method except `addCertificate`. If it were built, it would fail.
3. **No CI.** There is no `.github/workflows/`. Nothing runs `flutter test`, the Dart unit tests, or the native gtest/XCTest suites automatically.
4. **Weak integration assertion.** `example/integration_test/plugin_integration_test.dart` only asserts `isA<X509Failure>()`, which passes for any failure reason. It should assert a specific `X509ErrorCode`.

## Proposed work

- [ ] Add a gtest test target in `windows/CMakeLists.txt` (guarded, e.g. `if(BUILD_TESTING)`) so `windows/test/*.cpp` actually compiles and runs.
- [ ] Remove or fix the stale `GetPlatformVersion` gtest (plugin does not implement it).
- [ ] Add a GitHub Actions CI workflow: Dart `flutter test`, native Windows gtest, and (where feasible) macOS XCTest.
- [ ] Strengthen the integration test to assert a specific `X509ErrorCode` rather than any `X509Failure`.

## Why this matters

Until this exists, TDD is not possible on the native layers — the red-green feedback loop needs runnable tests. This is a prerequisite for verifying the regression test added in #7 and for test-first work on #8 / #10.

## Severity

P2 — test infrastructure; prerequisite for reliable native testing and TDD.
